# -*- coding: utf-8 -*-
"""home_page.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBL_AxpfC7rm22iC38wjXzCMX8zdvyfm
"""

import streamlit as st

st.set_page_config(
    page_title="Kingfisher Home Page",
    layout="centered"
)

st.markdown("""
<style>
    .main-header {color: #2e8b57; text-align: center; padding: 2rem 0;}
    .description {text-align: center; font-size: 1.2rem; color: #3c763d;}
</style>
""", unsafe_allow_html=True)
