# -*- coding: utf-8 -*-
"""home_page.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qBL_AxpfC7rm22iC38wjXzCMX8zdvyfm
"""

import streamlit as st
import geopandas as gpd
import folium
from streamlit_folium import st_folium

# st.set_page_config(
#     page_title="Kingfisher Home Page",
#     layout="centered"
# )

# st.markdown("""
# <style>
#     .main-header {color: #2e8b57; text-align: center; padding: 2rem 0;}
#     .description {text-align: center; font-size: 1.2rem; color: #3c763d;}
# </style>
# """, unsafe_allow_html=True)

# st.markdown("<h1 class='main-header'>Kingfisher Home Page</h1>", unsafe_allow_html=True)

st.set_page_config(
    page_title="Debris Visualization",
    layout="centered"
)

debris_gdf = gpd.read_file("detected_marine_debris.geojson")

if not debris_gdf.empty:
    st.subheader("Interactive Debris Map for Waterways")
    st.markdown("""
    <p class='description'>
    Welcome to our floater debris visualization to help you select the best location to deploy your Kingfisher.
    We have focused our data collection on inland waterways.
    It's recommended to select locations that show higher levels of floater debris along your chosen waterway. 
    <br><br>
    An example has been loaded below showing debris along Sacramento River.
    Click a dot to get its specific location.
    </p>
    """, unsafe_allow_html=True)

    # Center map
    center = [
        debris_gdf.geometry.y.mean(),
        debris_gdf.geometry.x.mean()
    ]

    m = folium.Map(location=center, zoom_start=8)

    for _, row in debris_gdf.iterrows():
        folium.CircleMarker(
            location=[row.geometry.y, row.geometry.x],
            radius=2,
            color="red",
            fill=True,
            fill_opacity=0.7,
            popup=(
                f"Latitude: {row.geometry.y}<br>"
                f"Longitude: {row.geometry.x}<br>"
                f"Confidence: {row['confidence_score']}<br>"
                f"Location: {row['location']}"
            ),
            tooltip=(
                f"Lat: {row.geometry.y}, "
                f"Lon: {row.geometry.x}, "
                f"Conf: {row['confidence_score']}"
            )
        ).add_to(m)

    output = st_folium(
        m,
        width=700,
        height=500,
        returned_objects=["last_clicked"]
    )
    
    if output.get("last_clicked"):
        st.write(output["last_clicked"])

else:
    st.warning("No debris detected to display on the map.")
