# -*- coding: utf-8 -*-
"""debris_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ezo-xQG8qJxwGk-9zzcN3UnkTPkLvTms
"""

import streamlit as st
import geopandas as gpd
from streamlit_folium import st_folium

debris_gdf = gpd.read_file("detected_marine_debris.geojson")

st.set_page_config(
    page_title="Debris Visualization",
    layout="centered"
)

if not debris_gdf.empty:
    st.subheader("Interactive Fluvian Debris Map")
    st.markdown("""
    <p class='description'>
        Welcome to our floater debris visualization to help you select the best location to deploy your Kingfisher.
        We have focused our data collection on inland waterways.
        It's recommended to select locations that show higher levels of floater debris along your chosen waterway. 
    </p>
    """, unsafe_allow_html=True)

    debris_gdf.explore(
        color='red',
        tooltip=['latitude', 'longitude', 'confidence_score'],
        popup=['latitude', 'longitude', 'confidence_score', 'location'],
        marker_kwds={'radius': 2},
        name="Detected Debris"
    )

    st_folium(m, width=700, height=500)
else:
    st.warning("No debris detected to display on the map.")
