# -*- coding: utf-8 -*-
"""debris_visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ezo-xQG8qJxwGk-9zzcN3UnkTPkLvTms
"""

import streamlit as st
import geopandas as gpd
from streamlit_folium import st_folium

debris_gdf = gpd.read_file("debris_gdf.geojson")

st.set_page_config(
    page_title="Debris Visualization",
    layout="centered"
)

if not debris_gdf.empty:
    st.subheader("Interactive Marine Debris Map")

    m = debris_gdf.explore()

    st_folium(m, width=700, height=500)
else:
    st.warning("No debris detected to display on the map.")
